// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD0BToDMJREYOlTSpxNihP__c4uC0tvnY',
    appId: '1:169392088588:web:6af9c03ce5c02fa4433029',
    messagingSenderId: '169392088588',
    projectId: 'campusserve-5f138',
    authDomain: 'campusserve-5f138.firebaseapp.com',
    storageBucket: 'campusserve-5f138.firebasestorage.app',
    measurementId: 'G-VT3CGSYN4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeWoM-oEFHdj5eExZ5InGOmqiza0gGRZw',
    appId: '1:169392088588:android:7d89c1203311f986433029',
    messagingSenderId: '169392088588',
    projectId: 'campusserve-5f138',
    storageBucket: 'campusserve-5f138.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7he3jpfrNeQifIUOATYA98R7n71CxiA8',
    appId: '1:169392088588:ios:97ff7e00c6f331d7433029',
    messagingSenderId: '169392088588',
    projectId: 'campusserve-5f138',
    storageBucket: 'campusserve-5f138.firebasestorage.app',
    iosClientId: '169392088588-2no6efvd45bmiifa3v1lk80kacnn5ev9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD0BToDMJREYOlTSpxNihP__c4uC0tvnY',
    appId: '1:169392088588:web:db03647c0f551f82433029',
    messagingSenderId: '169392088588',
    projectId: 'campusserve-5f138',
    authDomain: 'campusserve-5f138.firebaseapp.com',
    storageBucket: 'campusserve-5f138.firebasestorage.app',
    measurementId: 'G-2E1JLRZCZ0',
  );
}
